// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineMedicineStoreBackend.Data;

#nullable disable

namespace OnlineMedicineStoreBackend.Migrations
{
    [DbContext(typeof(OnlineMedicineStoreDbContext))]
    partial class OnlineMedicineStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Vietnamese_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.ChiTietDonHang", b =>
                {
                    b.Property<Guid>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_chi_tiet")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("don_gia");

                    b.Property<Guid>("MaDonHang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_don_hang");

                    b.Property<Guid>("MaLo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_lo");

                    b.Property<Guid>("MaThuoc")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_thuoc");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanh_tien")
                        .HasComputedColumnSql("([so_luong]*[don_gia])", true);

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaLo");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.ChiTietGioHang", b =>
                {
                    b.Property<Guid>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_chi_tiet")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("MaGioHang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_gio_hang");

                    b.Property<Guid>("MaThuoc")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_thuoc");

                    b.Property<DateTime>("NgayThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_them")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_luong");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.DanhMuc", b =>
                {
                    b.Property<Guid>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_danh_muc")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("DanhMucChaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("danh_muc_cha_id");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_danh_muc");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("DanhMucChaId");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.DiaChiKhachHang", b =>
                {
                    b.Property<Guid>("MaDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_dia_chi")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("HoTenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten_nguoi_nhan");

                    b.Property<bool>("LaMacDinh")
                        .HasColumnType("bit")
                        .HasColumnName("la_mac_dinh");

                    b.Property<Guid>("MaKhachHang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_khach_hang");

                    b.Property<string>("SDTNguoiNhan")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT_nguoi_nhan");

                    b.HasKey("MaDiaChi");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DiaChiKhachHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.DonHang", b =>
                {
                    b.Property<Guid>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_don_hang")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("giam_gia");

                    b.Property<string>("LoaiDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loai_don");

                    b.Property<Guid?>("MaDiaChi")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_dia_chi");

                    b.Property<Guid>("MaKhachHang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_khach_hang");

                    b.Property<Guid?>("MaNhanVien")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nhan_vien");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_dat")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("phi_van_chuyen");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phuong_thuc_TT");

                    b.Property<decimal>("TamTinh")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tam_tinh");

                    b.Property<decimal>("ThanhToan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanh_toan");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaDiaChi");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.GioHang", b =>
                {
                    b.Property<Guid>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_gio_hang")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("MaKhachHang")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_khach_hang");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaKhachHang")
                        .IsUnique()
                        .HasDatabaseName("uq_GioHang_khachhang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.KhachHang", b =>
                {
                    b.Property<Guid>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_khach_hang")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int")
                        .HasColumnName("diem_tich_luy");

                    b.Property<string>("HangThanhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("hang_thanh_vien");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nguoi_dung");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique()
                        .HasDatabaseName("uq_KhachHang_nguoidung");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.LoThuoc", b =>
                {
                    b.Property<Guid>("MaLo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_lo")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_nhap");

                    b.Property<Guid>("MaNhaCungCap")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nha_cung_cap");

                    b.Property<Guid>("MaPhieuNhap")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_phieu_nhap");

                    b.Property<Guid>("MaThuoc")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_thuoc");

                    b.Property<DateOnly>("NgayHetHan")
                        .HasColumnType("date")
                        .HasColumnName("ngay_het_han");

                    b.Property<DateOnly?>("NgaySanXuat")
                        .HasColumnType("date")
                        .HasColumnName("ngay_san_xuat");

                    b.Property<int>("SoLuongHienTai")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_hien_tai");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_nhap");

                    b.HasKey("MaLo");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaThuoc");

                    b.ToTable("LoThuocs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nguoi_dung")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vai_tro");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("TenDangNhap")
                        .IsUnique()
                        .HasDatabaseName("uq_NguoiDung_tendangnhap");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.NhaCungCap", b =>
                {
                    b.Property<Guid>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nha_cung_cap")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nguoi_lien_he");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_cong_ty");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.NhanVien", b =>
                {
                    b.Property<Guid>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nhan_vien")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chuc_vu");

                    b.Property<decimal?>("Luong")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("luong");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateOnly?>("NgayVaoLam")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_lam");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique()
                        .HasDatabaseName("uq_NhanVien_nguoidung");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.PhieuNhap", b =>
                {
                    b.Property<Guid>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_phieu_nhap")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid>("MaNhaCungCap")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nha_cung_cap");

                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_nhan_vien");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nhap");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.Thuoc", b =>
                {
                    b.Property<Guid>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_thuoc")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia_ban");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("hinh_anh");

                    b.Property<string>("HuongDanSuDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("huong_dan_su_dung");

                    b.Property<string>("LoaiThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("loai_thuoc");

                    b.Property<Guid>("MaDanhMuc")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ma_danh_muc");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenKhoaHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_khoa_hoc");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_thuoc");

                    b.Property<int>("TonKhoHienTai")
                        .HasColumnType("int")
                        .HasColumnName("ton_kho_hien_tai");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaThuoc");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("Thuocs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineMedicineStoreBackend.Models.LoThuoc", "LoThuoc")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaLo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineMedicineStoreBackend.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("LoThuoc");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineMedicineStoreBackend.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.DanhMuc", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.DanhMuc", "DanhMucCha")
                        .WithMany("DanhMucCons")
                        .HasForeignKey("DanhMucChaId");

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.DiaChiKhachHang", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.KhachHang", "KhachHang")
                        .WithMany("DiaChiKhachHangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.DonHang", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.DiaChiKhachHang", "DiaChiKhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaDiaChi")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineMedicineStoreBackend.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineMedicineStoreBackend.Models.NhanVien", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("DiaChiKhachHang");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.GioHang", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.KhachHang", "KhachHang")
                        .WithOne("GioHang")
                        .HasForeignKey("OnlineMedicineStoreBackend.Models.GioHang", "MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.KhachHang", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.NguoiDung", "NguoiDung")
                        .WithOne("KhachHang")
                        .HasForeignKey("OnlineMedicineStoreBackend.Models.KhachHang", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.LoThuoc", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("LoThuocs")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineMedicineStoreBackend.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("LoThuocs")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineMedicineStoreBackend.Models.Thuoc", "Thuoc")
                        .WithMany("LoThuocs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("PhieuNhap");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.NhanVien", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.NguoiDung", "NguoiDung")
                        .WithOne("NhanVien")
                        .HasForeignKey("OnlineMedicineStoreBackend.Models.NhanVien", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.PhieuNhap", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineMedicineStoreBackend.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.Thuoc", b =>
                {
                    b.HasOne("OnlineMedicineStoreBackend.Models.DanhMuc", "DanhMuc")
                        .WithMany("Thuocs")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.DanhMuc", b =>
                {
                    b.Navigation("DanhMucCons");

                    b.Navigation("Thuocs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.DiaChiKhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.KhachHang", b =>
                {
                    b.Navigation("DiaChiKhachHangs");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.LoThuoc", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.NguoiDung", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.NhaCungCap", b =>
                {
                    b.Navigation("LoThuocs");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.NhanVien", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.PhieuNhap", b =>
                {
                    b.Navigation("LoThuocs");
                });

            modelBuilder.Entity("OnlineMedicineStoreBackend.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("LoThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
